name: ci

on:
  pull_request:
    brancehs: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Force Failure
        run: (exit 1)
